
services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html/
      - ./docker/000-default.conf:/etc/apache2/site-enabled/000-default.conf
    networks:
      - default

  mysql:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: apachedb_dev
      MARIADB_USER: apachedb_user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
    links:
      - mysql
    ports:
      - 8085:80
    volumes:
      - /sessions
    networks:
      - default

  # postgres:
  #   image: postgres:14-alpine
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ~/docker/postgres:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_USER=apachedb_user
  #     - POSTGRES_DB=apachedb_dev
  #   networks:
  #     - default
  
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  database:
